name: Test
on:
  push:
    paths-ignore:
      - '.github/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "20.11.1"
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install
      - run: pnpm typecheck
      - run: pnpm biome:check
      - run: pnpm test
      - run: npx playwright install --with-deps
      - run: pnpm storybook:test:ci
